"""Add SalesOrderResolution model

Revision ID: 0455c870be67
Revises: abcd1234efgh
Create Date: 2026-07-20 13:50:52.615464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0455c870be67'
down_revision: Union[str, Sequence[str], None] = 'abcd1234efgh'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_order_resolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('resolution_type', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refund_account_details', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_order_resolution')
    # ### end Alembic commands ###
