"""multiple_receipts_quick_procurement

Revision ID: 0c6b1cd7690c
Revises: f3a4b5c6d7e8
Create Date: 2026-07-03 22:19:35.814791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6b1cd7690c'
down_revision: Union[str, Sequence[str], None] = 'f3a4b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('receipt_urls', sa.JSON(), nullable=True))
    
    bind = op.get_bind()
    if bind.engine.name == 'sqlite':
        bind.execute(sa.text("UPDATE expense SET receipt_urls = json_array(receipt_url) WHERE receipt_url IS NOT NULL"))
        bind.execute(sa.text("UPDATE expense SET receipt_urls = json_array() WHERE receipt_url IS NULL"))
    else:
        bind.execute(sa.text("UPDATE expense SET receipt_urls = json_build_array(receipt_url) WHERE receipt_url IS NOT NULL"))
        bind.execute(sa.text("UPDATE expense SET receipt_urls = '[]'::jsonb WHERE receipt_url IS NULL"))
        
    with op.batch_alter_table('expense') as batch_op:
        batch_op.alter_column('receipt_urls', nullable=False)
        batch_op.drop_column('receipt_url')
        
    op.add_column('fabric_lot', sa.Column('expense_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('fabric_lot') as batch_op:
        batch_op.create_foreign_key('fk_fabric_lot_expense_id', 'expense', ['expense_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fabric_lot') as batch_op:
        batch_op.drop_constraint('fk_fabric_lot_expense_id', type_='foreignkey')
        batch_op.drop_column('expense_id')
    op.add_column('expense', sa.Column('receipt_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    bind = op.get_bind()
    if bind.engine.name == 'sqlite':
        bind.execute(sa.text("UPDATE expense SET receipt_url = json_extract(receipt_urls, '$[0]') WHERE json_array_length(receipt_urls) > 0"))
    else:
        bind.execute(sa.text("UPDATE expense SET receipt_url = receipt_urls->>0 WHERE jsonb_array_length(receipt_urls::jsonb) > 0"))
        
    with op.batch_alter_table('expense') as batch_op:
        batch_op.drop_column('receipt_urls')
    # ### end Alembic commands ###
