"""add labor_cost to stitching_batch

Revision ID: 23acf63d71f9
Revises: 7b1f898f30fd
Create Date: 2026-06-27 21:56:22.324445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23acf63d71f9'
down_revision: Union[str, Sequence[str], None] = '7b1f898f30fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stitching_batch', sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stitching_batch', 'labor_cost')
    # ### end Alembic commands ###
