"""Add PageVisit model

Revision ID: 2619bd60e9a3
Revises: 171587ee0754
Create Date: 2026-08-28 15:05:27.132858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2619bd60e9a3'
down_revision: Union[str, Sequence[str], None] = '171587ee0754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_visit_created_at'), 'page_visit', ['created_at'], unique=False)
    op.create_index(op.f('ix_page_visit_session_id'), 'page_visit', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_visit_session_id'), table_name='page_visit')
    op.drop_index(op.f('ix_page_visit_created_at'), table_name='page_visit')
    op.drop_table('page_visit')
    # ### end Alembic commands ###
