"""add order tracking

Revision ID: 27710b99f818
Revises: h6i7j8k9l0m1
Create Date: 2026-08-04 01:13:21.253084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27710b99f818'
down_revision: Union[str, Sequence[str], None] = 'h6i7j8k9l0m1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('sales_order', sa.Column('utr_number', sa.String(), nullable=True))
    op.add_column('sales_order', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales_order', sa.Column('raw_items', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order', 'raw_items')
    op.drop_column('sales_order', 'settled_at')
    op.drop_column('sales_order', 'utr_number')
    op.drop_column('sales_order', 'razorpay_order_id')
    # ### end Alembic commands ###
