"""add shiprocket fields

Revision ID: 44f4dcee80f1
Revises: b7d76bb2644a
Create Date: 2026-08-04 21:10:41.855326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f4dcee80f1'
down_revision: Union[str, Sequence[str], None] = 'b7d76bb2644a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order', sa.Column('customer_city', sa.String(), nullable=True))
    op.add_column('sales_order', sa.Column('customer_pincode', sa.String(), nullable=True))
    op.add_column('sales_order', sa.Column('customer_email', sa.String(), nullable=True))
    op.add_column('sales_order', sa.Column('shiprocket_order_id', sa.Integer(), nullable=True))
    op.add_column('sales_order', sa.Column('shiprocket_shipment_id', sa.Integer(), nullable=True))
    op.add_column('sales_order', sa.Column('shiprocket_awb', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order', 'shiprocket_awb')
    op.drop_column('sales_order', 'shiprocket_shipment_id')
    op.drop_column('sales_order', 'shiprocket_order_id')
    op.drop_column('sales_order', 'customer_email')
    op.drop_column('sales_order', 'customer_pincode')
    op.drop_column('sales_order', 'customer_city')
    # ### end Alembic commands ###
