"""add gstin to customer

Revision ID: 4cb1a37a1ed0
Revises: 44f4dcee80f1
Create Date: 2026-08-05 15:19:43.704197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb1a37a1ed0'
down_revision: Union[str, Sequence[str], None] = '44f4dcee80f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('gstin', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'gstin')
    # ### end Alembic commands ###
