"""add campaign_id to sales_order

Revision ID: 80490f035d51
Revises: 0455c870be67
Create Date: 2026-07-25 18:08:48.402182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80490f035d51'
down_revision: Union[str, Sequence[str], None] = '0455c870be67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order', sa.Column('campaign_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order', 'campaign_id')
    # ### end Alembic commands ###
