"""add payment fields to proforma_invoice

Revision ID: 9ab7c793281a
Revises: e00b4e76815d
Create Date: 2026-08-05 18:16:21.099178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab7c793281a'
down_revision: Union[str, Sequence[str], None] = 'e00b4e76815d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proforma_invoice', sa.Column('advance_payment_mode', sa.String(), nullable=True))
    op.add_column('proforma_invoice', sa.Column('advance_payment_notes', sa.String(), nullable=True))
    op.add_column('proforma_invoice', sa.Column('balance_payment_mode', sa.String(), nullable=True))
    op.add_column('proforma_invoice', sa.Column('balance_payment_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proforma_invoice', 'balance_payment_notes')
    op.drop_column('proforma_invoice', 'balance_payment_mode')
    op.drop_column('proforma_invoice', 'advance_payment_notes')
    op.drop_column('proforma_invoice', 'advance_payment_mode')
    # ### end Alembic commands ###
