"""add_image_urls_and_expenses

Revision ID: afaa38bf4300
Revises: 23acf63d71f9
Create Date: 2026-07-02 10:39:01.375277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afaa38bf4300'
down_revision: Union[str, Sequence[str], None] = '23acf63d71f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('paid_to', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fabric_item', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('style', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('style', 'image_url')
    op.drop_column('fabric_item', 'image_url')
    op.drop_table('expense')
    op.drop_table('expense_category')
    # ### end Alembic commands ###
