"""initial schema

Revision ID: b61d80ea9706
Revises: 
Create Date: 2026-06-27 01:46:01.472455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b61d80ea9706'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('consumption_uom', sa.String(), nullable=False),
    sa.Column('default_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fabric_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('composition', sa.String(), nullable=True),
    sa.Column('gsm', sa.Integer(), nullable=True),
    sa.Column('width', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('consumption_uom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('collection', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_of_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accessory_ledger_entry',
    sa.Column('accessory_item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('txn_type', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accessory_item_id'], ['accessory_item.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('active_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('sku_code', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_code')
    )
    op.create_table('uom_conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_uom_id', sa.Integer(), nullable=False),
    sa.Column('to_uom_id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['from_uom_id'], ['unit_of_measure.id'], ),
    sa.ForeignKeyConstraint(['to_uom_id'], ['unit_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_uom_id', 'to_uom_id')
    )
    op.create_table('bom_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finished_goods_ledger_entry',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('txn_type', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['style_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('ordered_qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ordered_uom', sa.String(), nullable=False),
    sa.Column('agreed_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_version_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('qty_per_unit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bom_version_id'], ['bom_version.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['style_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fabric_lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabric_item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=True),
    sa.Column('dye_lot_no', sa.String(), nullable=True),
    sa.Column('received_qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cost_per_uom', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['fabric_item_id'], ['fabric_item.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['purchase_order_line.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('bom_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bom_version_id'], ['bom_version.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cutting_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('fabric_lot_id', sa.Integer(), nullable=False),
    sa.Column('planned_fabric_qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_fabric_qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cut_pieces_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wastage_qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['fabric_lot_id'], ['fabric_lot.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fabric_ledger_entry',
    sa.Column('fabric_lot_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('txn_type', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fabric_lot_id'], ['fabric_lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landed_cost_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabric_lot_id', sa.Integer(), nullable=False),
    sa.Column('expense_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['fabric_lot_id'], ['fabric_lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_order_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('planned_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['style_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stitching_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('in_house', sa.Boolean(), nullable=False),
    sa.Column('sent_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rejected_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('qc_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rework_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_stitching_batch_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_stitching_batch_id'], ['stitching_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rework_record')
    op.drop_table('stitching_batch')
    op.drop_table('production_order_variant')
    op.drop_table('production_event')
    op.drop_table('landed_cost_entry')
    op.drop_table('fabric_ledger_entry')
    op.drop_table('cutting_record')
    op.drop_table('production_order')
    op.drop_table('fabric_lot')
    op.drop_table('bom_item')
    op.drop_table('purchase_order_line')
    op.drop_table('finished_goods_ledger_entry')
    op.drop_table('bom_version')
    op.drop_table('uom_conversion')
    op.drop_table('style_variant')
    op.drop_table('purchase_order')
    op.drop_table('bom')
    op.drop_table('accessory_ledger_entry')
    op.drop_table('warehouse')
    op.drop_table('unit_of_measure')
    op.drop_table('supplier')
    op.drop_table('style')
    op.drop_table('fabric_item')
    op.drop_table('accessory_item')
    # ### end Alembic commands ###
