"""add totals to sales order

Revision ID: b7d76bb2644a
Revises: 27710b99f818
Create Date: 2026-08-04 15:26:38.087022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d76bb2644a'
down_revision: Union[str, Sequence[str], None] = '27710b99f818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('sales_order', sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('sales_order', sa.Column('discount_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order', 'discount_code')
    op.drop_column('sales_order', 'discount_amount')
    op.drop_column('sales_order', 'total_amount')
    # ### end Alembic commands ###
