"""add gst_percent to proforma_line

Revision ID: e00b4e76815d
Revises: 4cb1a37a1ed0
Create Date: 2026-08-05 18:14:03.323053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00b4e76815d'
down_revision: Union[str, Sequence[str], None] = '4cb1a37a1ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proforma_invoice_line', sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proforma_invoice_line', 'gst_percent')
    # ### end Alembic commands ###
